### ISSUE TITLE
Missing Scott and Wenzel portrait

### ISSUE THREAD

**Issue by Al1284** [shinkiseki/MorePortraitsInAzure#7]
On chapter 3, day 2 on Tangram Gate.
![image](https://user-images.githubusercontent.com/57627886/227857580-53d630f8-f6f0-49a1-a2fb-a4078adbe024.png)

**Comment by shinkiseki** [comment]
Thanks for catching this! I missed not only this line but the entire file. This should be fixed as of the release of v0.2.0, so I'll close this issue. Feel free to reopen this if you still see this issue in the latest release.
