### ISSUE TITLE
Examine Trails to Azure HD portraits

### ISSUE THREAD

**Issue by shinkiseki** [shinkiseki/MorePortraitsInAzure#8]
Check this mod: https://www.reddit.com/r/Falcom/comments/nyek5s/trails_to_azure_hd_texture_mod_20_new_hd/

Examine whether the image quality is good enough to consider using over the NISA version

**Comment by shinkiseki** [comment]
Permission secured -- this will be integrated in a future version

**Comment by dmjohn0x** [comment]
This is outstanding news!

**Comment by shinkiseki** [comment]
Added!
